// Mock data for development without Firebase Admin SDK
export const mockQuizzes = [
  {
    id: 'quiz1',
    title: 'JavaScript Basics',
    description: 'Test your knowledge of JavaScript fundamentals',
    category: 'Programming',
    totalQuestions: 10,
    createdBy: 'BX682JjCbVez5CdN2sEX',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    isPublic: true,
    difficulty: 'Beginner',
    settings: {
      questionsPerGame: 5,
      allowReplays: true,
      showCorrectAnswers: true,
      randomizeQuestions: false,
      randomizeOptions: false,
    },
  },
  {
    id: 'quiz2',
    title: 'React Advanced Patterns',
    description: 'Learn advanced React patterns and best practices',
    category: 'Programming',
    totalQuestions: 15,
    createdBy: 'BX682JjCbVez5CdN2sEX',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
    isPublic: true,
    difficulty: 'Intermediate',
    settings: {
      questionsPerGame: 5,
      allowReplays: true,
      showCorrectAnswers: true,
      randomizeQuestions: false,
      randomizeOptions: false,
    },
  },
  {
    id: 'quiz3',
    title: 'TypeScript Generics',
    description: 'Master TypeScript generics and advanced types',
    category: 'Programming',
    totalQuestions: 12,
    createdBy: 'BX682JjCbVez5CdN2sEX',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
    isPublic: false,
    difficulty: 'Advanced',
    settings: {
      questionsPerGame: 6,
      allowReplays: true,
      showCorrectAnswers: true,
      randomizeQuestions: false,
      randomizeOptions: false,
    },
  },
  {
    id: 'quiz4',
    title: 'Quiz de Prueba',
    description: 'Un quiz simple para testing',
    category: 'General',
    totalQuestions: 1,
    createdBy: 'user3',
    createdAt: new Date('2024-03-06'),
    updatedAt: new Date('2024-03-06'),
    isPublic: true,
    difficulty: 'Beginner',
    settings: {
      questionsPerGame: 1,
      allowReplays: true,
      showCorrectAnswers: true,
      randomizeQuestions: false,
      randomizeOptions: false,
    },
  },
];

export const mockQuestions = {
  quiz1: [
    {
      id: 'q1',
      quizId: 'quiz1',
      text: 'What is the output of typeof undefined?',
      options: ['undefined', 'null', 'object', 'undefine'],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q2',
      quizId: 'quiz1',
      text: 'Which method removes the last element from an array?',
      options: ['pop()', 'push()', 'shift()', 'unshift()'],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q3',
      quizId: 'quiz1',
      text: 'What does destructuring do?',
      options: [
        'Extracts values from objects or arrays',
        'Deletes values from arrays',
        'Copies object properties',
        'None of the above',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q4',
      quizId: 'quiz1',
      text: 'Which is not a primitive type in JavaScript?',
      options: ['string', 'number', 'array', 'boolean'],
      correctAnswer: 2,
      difficulty: 'Beginner',
    },
    {
      id: 'q5',
      quizId: 'quiz1',
      text: 'What does the spread operator (...) do?',
      options: [
        'Spreads elements of an array',
        'Creates a new array',
        'Both A and B',
        'Neither A nor B',
      ],
      correctAnswer: 2,
      difficulty: 'Beginner',
    },
    {
      id: 'q6',
      quizId: 'quiz1',
      text: 'What is a closure?',
      options: [
        'A function with access to outer function variables',
        'A loop that closes',
        'A closed bracket',
        'A finished promise',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q7',
      quizId: 'quiz1',
      text: 'Which statement is true about const?',
      options: [
        'Variables cannot be reassigned',
        'Variables cannot be redeclared',
        'Variables are block-scoped',
        'All of the above',
      ],
      correctAnswer: 3,
      difficulty: 'Beginner',
    },
    {
      id: 'q8',
      quizId: 'quiz1',
      text: 'What is the purpose of the "this" keyword?',
      options: [
        'Refers to the current object',
        'Creates a new object',
        'Deletes an object',
        'Clones an object',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q9',
      quizId: 'quiz1',
      text: 'Which is an array method for transforming elements?',
      options: ['map()', 'filter()', 'reduce()', 'All of the above'],
      correctAnswer: 3,
      difficulty: 'Beginner',
    },
    {
      id: 'q10',
      quizId: 'quiz1',
      text: 'What is the difference between == and ===?',
      options: [
        '=== checks type, == does not',
        '== checks type, === does not',
        'There is no difference',
        'They are used in different contexts',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q11',
      quizId: 'quiz1',
      text: 'What does JSON.stringify do?',
      options: [
        'Converts object to string',
        'Parses string to object',
        'Validates JSON',
        'Both A and C',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q12',
      quizId: 'quiz1',
      text: 'What is NaN?',
      options: [
        'Not a Number',
        'Null and Nothing',
        'None and Null',
        'Negative and Not',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q13',
      quizId: 'quiz1',
      text: 'How do you check if a value is an array?',
      options: [
        'Array.isArray()',
        'typeof arr === "array"',
        'arr instanceof Array',
        'Both A and C',
      ],
      correctAnswer: 3,
      difficulty: 'Beginner',
    },
    {
      id: 'q14',
      quizId: 'quiz1',
      text: 'What does Object.keys() return?',
      options: [
        'An array of object keys',
        'An array of object values',
        'An object with keys',
        'A string of keys',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q15',
      quizId: 'quiz1',
      text: 'What is event bubbling?',
      options: [
        'Events propagate from child to parent',
        'Events propagate from parent to child',
        'Events stop at target',
        'Events are delayed',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q16',
      quizId: 'quiz1',
      text: 'What does parseInt() do?',
      options: [
        'Converts string to integer',
        'Parses entire object',
        'Converts integer to string',
        'Parses JSON',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q17',
      quizId: 'quiz1',
      text: 'What is hoisting?',
      options: [
        'Moving declarations to top of scope',
        'Lifting DOM elements',
        'Object climbing',
        'String parsing',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q18',
      quizId: 'quiz1',
      text: 'What does Object.assign() do?',
      options: [
        'Copies properties from one object to another',
        'Assigns value to variable',
        'Creates new object',
        'Deletes object properties',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q19',
      quizId: 'quiz1',
      text: 'What is the scope chain?',
      options: [
        'The order of scope lookup',
        'A list of variables',
        'A type of loop',
        'A debugging tool',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q20',
      quizId: 'quiz1',
      text: 'What does Promise.all() do?',
      options: [
        'Waits for all promises to resolve',
        'Executes promises sequentially',
        'Returns first resolved promise',
        'Rejects all promises',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q21',
      quizId: 'quiz1',
      text: 'What is async/await?',
      options: [
        'Syntactic sugar for promises',
        'A type of variable',
        'An HTML attribute',
        'A CSS property',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q22',
      quizId: 'quiz1',
      text: 'What does try/catch do?',
      options: [
        'Handles errors',
        'Throws errors',
        'Catches variables',
        'Tries to run code',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q23',
      quizId: 'quiz1',
      text: 'What is a callback function?',
      options: [
        'A function passed as argument',
        'A function that returns value',
        'A function in callback.js',
        'A function that calls itself',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q24',
      quizId: 'quiz1',
      text: 'What does setTimeout do?',
      options: [
        'Executes code after delay',
        'Sets a timer',
        'Stops execution',
        'Returns current time',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q25',
      quizId: 'quiz1',
      text: 'What is the event loop?',
      options: [
        'Manages async code execution',
        'A loop in events.js',
        'A browser feature',
        'Both A and C',
      ],
      correctAnswer: 3,
      difficulty: 'Beginner',
    },
    {
      id: 'q26',
      quizId: 'quiz1',
      text: 'What does filter() return?',
      options: [
        'A new filtered array',
        'A boolean value',
        'The original array',
        'null',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q27',
      quizId: 'quiz1',
      text: 'What is template literal syntax?',
      options: [
        'Using backticks for strings',
        'Using quotes for strings',
        'Using braces for strings',
        'Using quotes for variables',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q28',
      quizId: 'quiz1',
      text: 'What does isNaN() check?',
      options: [
        'If value is NaN',
        'If value is a number',
        'If value exists',
        'If value is null',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q29',
      quizId: 'quiz1',
      text: 'What is the difference between slice and splice?',
      options: [
        'slice creates new array, splice modifies original',
        'splice creates new array, slice modifies original',
        'They do the same thing',
        'Only slice works on arrays',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q30',
      quizId: 'quiz1',
      text: 'What does includes() do?',
      options: [
        'Checks if array contains element',
        'Adds element to array',
        'Removes element from array',
        'Returns index of element',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q31',
      quizId: 'quiz1',
      text: 'What is function declaration vs expression?',
      options: [
        'Declaration is hoisted, expression is not',
        'Both are hoisted',
        'Neither are hoisted',
        'Expression is hoisted, declaration is not',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q32',
      quizId: 'quiz1',
      text: 'What does document.querySelector do?',
      options: [
        'Selects first matching element',
        'Selects all matching elements',
        'Queries the database',
        'Selects by tag name only',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q33',
      quizId: 'quiz1',
      text: 'What is event delegation?',
      options: [
        'Handling events on parent for delegation',
        'Copying events',
        'Deleting events',
        'Creating new events',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q34',
      quizId: 'quiz1',
      text: 'What does forEach do?',
      options: [
        'Iterates over each element',
        'Finds first element',
        'Creates new array',
        'Stops iteration',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q35',
      quizId: 'quiz1',
      text: 'What is REST API?',
      options: [
        'Architecture for web services',
        'A type of database',
        'JavaScript method',
        'HTML element',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q36',
      quizId: 'quiz1',
      text: 'What is localStorage?',
      options: [
        'Stores data in browser',
        'Stores data on server',
        'A CSS property',
        'A JavaScript library',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q37',
      quizId: 'quiz1',
      text: 'What does fetch() do?',
      options: [
        'Makes HTTP requests',
        'Retrieves local files',
        'Loads CSS files',
        'Both A and B',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q38',
      quizId: 'quiz1',
      text: 'What is an IIFE?',
      options: [
        'Immediately Invoked Function Expression',
        'A type of variable',
        'An HTML element',
        'A CSS framework',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q39',
      quizId: 'quiz1',
      text: 'What is currying?',
      options: [
        'Transform function with multiple args to single args',
        'A cooking method',
        'A CSS selector',
        'A JavaScript event',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
    {
      id: 'q40',
      quizId: 'quiz1',
      text: 'What is memoization?',
      options: [
        'Caching function results',
        'Deleting data',
        'Memory management',
        'A browser feature',
      ],
      correctAnswer: 0,
      difficulty: 'Beginner',
    },
  ],
  quiz2: [
    {
      id: 'q11',
      quizId: 'quiz2',
      text: 'What is a render prop in React?',
      options: [
        'A prop that is a function returning JSX',
        'A prop used to render components',
        'A prop for styling',
        'A custom React hook',
      ],
      correctAnswer: 0,
      difficulty: 'Intermediate',
    },
    {
      id: 'q12',
      quizId: 'quiz2',
      text: 'What problem does React.memo solve?',
      options: [
        'Prevents unnecessary re-renders',
        'Improves useState',
        'Manages context better',
        'Replaces useCallback',
      ],
      correctAnswer: 0,
      difficulty: 'Intermediate',
    },
    {
      id: 'q13',
      quizId: 'quiz2',
      text: 'When would you use useCallback?',
      options: [
        'To memoize a function',
        'To optimize performance',
        'To prevent function recreation',
        'All of the above',
      ],
      correctAnswer: 3,
      difficulty: 'Intermediate',
    },
    {
      id: 'q14',
      quizId: 'quiz2',
      text: 'What is compound component pattern?',
      options: [
        'Components that work together through context',
        'Multiple components composed as one',
        'A component with compound selector',
        'None of the above',
      ],
      correctAnswer: 1,
      difficulty: 'Intermediate',
    },
    {
      id: 'q15',
      quizId: 'quiz2',
      text: 'How do you access previous props in a class component?',
      options: [
        'this.prevProps',
        'this.props is always current',
        'Use componentDidUpdate lifecycle',
        'React does not support this',
      ],
      correctAnswer: 2,
      difficulty: 'Intermediate',
    },
  ],
  quiz3: [
    {
      id: 'q16',
      quizId: 'quiz3',
      text: 'What is a generic type parameter in TypeScript?',
      options: [
        'A placeholder for any type',
        'A way to create reusable components',
        'A TypeScript-only feature',
        'Both A and B',
      ],
      correctAnswer: 3,
      difficulty: 'Advanced',
    },
    {
      id: 'q17',
      quizId: 'quiz3',
      text: 'What does "extends" do in generics?',
      options: [
        'Constrains a generic type',
        'Inherits from a class',
        'Creates a new interface',
        'Defines an intersection type',
      ],
      correctAnswer: 0,
      difficulty: 'Advanced',
    },
    {
      id: 'q18',
      quizId: 'quiz3',
      text: 'What is a mapped type?',
      options: [
        'A type that transforms properties of another type',
        'A way to map values',
        'A type for map objects',
        'A TypeScript decorator',
      ],
      correctAnswer: 0,
      difficulty: 'Advanced',
    },
  ],
  quiz4: [
    {
      id: 'q41',
      quizId: 'quiz4',
      text: '¿Cuál es la capital de Francia?',
      options: ['Londres', 'París', 'Madrid', 'Roma'],
      correctAnswer: 1,
      difficulty: 'Beginner',
    },
  ],
};

export const mockGameSessions = [
  {
    id: 'session1',
    quizId: 'quiz1',
    userId: 'BX682JjCbVez5CdN2sEX',
    score: 85,
    questionsAttempted: 5,
    correctAnswers: 4,
    completedAt: new Date('2024-01-25'),
  },
  {
    id: 'session2',
    quizId: 'quiz2',
    userId: 'BX682JjCbVez5CdN2sEX',
    score: 75,
    questionsAttempted: 5,
    correctAnswers: 3,
    completedAt: new Date('2024-02-05'),
  },
];

// Mock users for development (passwords are hashed with bcrypt)
// user1: email=user@example.com, password=password123
// user2: email=tecnicodeservicios@valserindustriales.com, password=password123
export const mockUsers = [
  {
    id: 'BX682JjCbVez5CdN2sEX',
    email: 'tecnicodeservicios@valserindustriales.com',
    name: 'Wilder',
    password: '$2a$10$K8HYc9w7k8k5.7GKDzXrv.K8HYc9w7k8k5.7GKDzXrv', // password123 (pre-hashed for demo)
    avatar: null,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user2',
    email: 'user@example.com',
    name: 'Test User',
    password: '$2a$10$K8HYc9w7k8k5.7GKDzXrv.K8HYc9w7k8k5.7GKDzXrv', // password123
    avatar: null,
    createdAt: new Date('2024-01-01'),
  },
  {
    id: 'user3',
    email: 'test@example.com',
    name: 'Local Test',
    password: '$2b$10$FGJRjxH9uSZNUWx.rIkOC.Bmwa0kluTdB2a4Uf0PGV.M4CPy7a3SG', // Password123!
    avatar: null,
    createdAt: new Date(),
  },
];
